version: '3.8'
services:
  api:
    build: ./api
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '8080:8080'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
